/*
 SAVE CREEN E RESTORE SCREEN
*/

PROCEDURE MAIN
    LOCAL CSCREEN 
    LOCAL X, Y, Z

    CLS 

    @ 10, 10 TO 12, 74
    @ 11, 11 SAY PADC ("ESSA TELA SERA RESTAURADA AO FINAL", 60)
    SAVE SCREEN TO CSCREEN 

    ?
    WAIT "TELE ALGO PARA CONTINUAR"
    CLS

    ?
    ? "APLICACAO DA FORMULA"
    ?
    INPUT "INSIRA O VALOR DE X: " TO X
    INPUT "INSIRA O VALOR DE Y: " TO Y
    Z = ( 1 / (X + Y))
    ?
    ? "O VALOR DE Z E: " , Z 
    ?
    WAIT "TECLE ALGO PARA RESTAURAR A TELA ANTERIOR"
    RESTORE SCREEN FROM CSCREEN

RETURN

