*  Sistema.....: ZIUL - Cobranca da manutencao
*  Programador.: Nando                                                  
*  Data........: 22/02/2021                                                 
*  Programa....: ENV_BOLS.PRG
*  Descricao...: Envia boletos Itau por e-mail
*  Alteracao...: 
*  Data........:                                                  
*  Feita por...:
*
******************** Envia boletos Itau por e-mail ********************
*--------------------*
 Procedure ENVIA_BOLS
*--------------------*
  clear screen

  *..... Rotina para enviar boletos da cobranca por E-mail para os clientes

  alert("Rotina para enviar boletos. Em desenvolvimento")

  return
*
**************************************** fim *************************************
